##################################################
#
# cypress image
FROM cypress/included:13.10.0

ENV CYPRESS_CACHE_FOLDER=/opt/console/frontend/cypress_cache

RUN mkdir -p /opt/console/frontend/cypress_cache
RUN mkdir -p /tmp/artifacts

COPY analyze.sh test-cypress.sh test-demos.sh test-frontend.sh test-prow-e2e.sh /opt/console/
COPY frontend/ /opt/console/frontend/

# WORKDIR /opt/console/frontend
# RUN yarn install
WORKDIR /opt/console/
# doesn't require a root user.
# USER 1001

LABEL io.k8s.display-name="OpenShift Console frontend CI/CD image" \
    io.k8s.description="Image used for testing console frontend in CI/CD" \
    io.openshift.tags="openshift" \
    maintainer="Jakub Hadvig <jhadvig@redhat.com>"

# CMD [ "/opt/bridge/bin/bridge", "--public-dir=/opt/bridge/static" ]


