apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-console-extension-crd
  namespace: myproject
rules:
  - apiGroups:
      - extensions
    resources:
      - consoleextensions
    verbs:
      - get
      - list
      - watch